name: Connect_EC2

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Repository name to pass into script"
        required: true
        type: string

jobs:
  connect_ec2:
    runs-on: self-hosted   # must match the label you registered for your runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform init -upgrade

      - name: Apply Terraform
        run: terraform apply -auto-approve
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq  
      - name: Get Terraform outputs
        id: tf_outputs
        run: |
         echo "INSTANCE_ID=$(terraform output -json | jq -r '.app_instance_id.value')" >> $GITHUB_ENV
         echo "PUBLIC_IP=$(terraform output -json | jq -r '.app_instance_public_ip.value')" >> $GITHUB_ENV
         echo "AZ=$(terraform output -json | jq -r '.app_instance_az.value')" >> $GITHUB_ENV
  

      - name: Connect to EC2
        run: |
          chmod +x postTerraformscript.sh
          ./postTerraformscript.sh "${{ inputs.repo_name }}"
