name: connect_EC2

on:
  workflow_call:
    inputs:
      repo_name:
        description: "Repository name to pass into script"
        required: true
        type: string

jobs:
  connect_ec2:
    runs-on: self-hosted   # must match the label you registered for your runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform init -upgrade

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Connect to EC2
        run: |
          chmod +x postTerraformscript.sh
          ./postTerraformscript.sh "${{ inputs.repo_name }}"
